# Generated by Django 5.0.6 on 2024-07-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_genres_movies_geners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='geners',
        ),
        migrations.AddField(
            model_name='movies',
            name='geners',
            field=models.ManyToManyField(related_name='movies', to='recommend.genres'),
        ),
    ]
