# Generated by Django 5.0.6 on 2024-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_rename_geners_movies_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
