# Generated by Django 5.0.6 on 2024-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_movies_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trendingmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('poster_url', models.CharField(blank=True, max_length=300, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=300, null=True)),
                ('actors', models.CharField(blank=True, max_length=300, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('poster_path', models.CharField(blank=True, max_length=300, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('budget', models.FloatField(default=0)),
                ('homepage', models.CharField(blank=True, max_length=300, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('revenue', models.FloatField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_count', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('tag', models.CharField(choices=[('normal', 'normal'), ('popular', 'popular'), ('upcomming', 'upcomming'), ('top_rated', 'top_rated'), ('most_reviewd', 'most_reviewd')], default='normal', max_length=30)),
                ('genres', models.ManyToManyField(related_name='trendingmovie', to='recommend.genres')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
