# Generated by Django 5.0.6 on 2024-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_alter_movies_adult_alter_movies_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
