# Generated by Django 5.0.6 on 2024-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_movies_movie_id_trendingmovie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tag',
            field=models.CharField(choices=[('normal', 'normal'), ('popular', 'popular'), ('upcomming', 'upcomming'), ('top_rated', 'top_rated'), ('most_reviewd', 'most_reviewd'), ('trending', 'trending')], default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='trendingmovie',
            name='tag',
            field=models.CharField(choices=[('normal', 'normal'), ('popular', 'popular'), ('upcomming', 'upcomming'), ('top_rated', 'top_rated'), ('most_reviewd', 'most_reviewd'), ('trending', 'trending')], default='normal', max_length=30),
        ),
    ]
