# Generated by Django 5.1 on 2024-09-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_alter_movies_tag_alter_trendingmovie_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tag',
            field=models.CharField(choices=[('normal', 'normal'), ('popular', 'popular'), ('upcomming', 'upcomming'), ('top_rated', 'top_rated'), ('most_reviewed', 'most_reviewed'), ('trending', 'trending')], default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='trendingmovie',
            name='tag',
            field=models.CharField(choices=[('normal', 'normal'), ('popular', 'popular'), ('upcomming', 'upcomming'), ('top_rated', 'top_rated'), ('most_reviewed', 'most_reviewed'), ('trending', 'trending')], default='normal', max_length=30),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('review', models.CharField(blank=True, max_length=400, null=True)),
                ('rating', models.IntegerField(default=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
